---
- name: Install Zsh, Oh My Zsh, Go, Node.js, Yarn, and Git on macOS
  hosts: localhost
  tasks:
    - name: Install Zsh
      homebrew:
        name: zsh
        state: present

    - name: Ensure Zsh is the default shell
      command: chsh -s $(which zsh)
      args:
        creates: ~/.zshrc

    - name: Install Oh My Zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh

    - name: Install Node.js
      homebrew:
        name: node
        state: present

    - name: Install Yarn
      homebrew:
        name: yarn
        state: present

    - name: Install Git
      homebrew:
        name: git
        state: present

    - name: Append Zsh configurations to .zshrc
      lineinfile:
        path: ~/.zshrc
        line: "{{ item }}"
        state: present
      loop:
        - "# Theme configuration"
        - 'ZSH_THEME="robbyrussell"'
        - "# Enable plugins"
        - "plugins=(git zsh-autosuggestions)"
        - "# Source Oh My Zsh and NVM"
        - "source $ZSH/oh-my-zsh.sh"
        - "source ~/.nvm/nvm.sh"
        - "# Aliases"
        - 'alias y-mweb="yarn workspace website dev-mweb"'
        - 'alias y-web="yarn workspace website dev"'
        - 'alias yw-dnext="cd packages/website; rm -rf .next; cd ../..;"'
        - 'alias jestcomp="yarn jest $(pwd)/"'
        - 'alias y-lr="yarn workspace main dev"'
        - 'alias yl-dnext="cd packages/main; rm -rf .next; cd ../..;"'
        - 'alias vz="vim ~/.zshrc"'
        - 'alias sz="source ~/.zshrc"'
        - 'alias mp="make sync TEAMS=payments"'
        - 'alias gpmp="ga .; gcmsg \\"Make sync\\"; gp"'
        - "# Go environment variables"
        - 'export GOPATH="${HOME}/go"'
        - 'export GOBIN="${GOPATH}/bin"'
        - 'export GOROOT="$(brew --prefix go@1.19)/libexec"'
        - "# Update PATH"
        - 'export PATH="$HOME/.console-ninja/.bin:$PATH:${GOPATH}/bin:${GOROOT}/bin"'
        - 'test -d "${GOPATH}" || mkdir -p "${GOPATH}"'
        - 'test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"'
        - "# Source GVM if installed"
        - '[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"'
